server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yanguowei/spring-cloud-starter/
          search-paths: config-repo
          username: yanguowei
          password: